#!/usr/bin/env ruby
# -*- mode: ruby; coding: utf-8 -*-

BEGIN {
  $LOAD_PATH.push File.dirname($0)
}

require 'TransitionTask'

begin
  user = `logname`.chop
  group = `id -g #{user}`.chop

  task = TransitionTask.new(user, group)
  task.execute
end
